Repository Kernel360/KDEV3_FlowSync_BE, pull requests merged in 2025-01, with the labels that each got.

#61 feat: BaseEntity, AuditorAware 추가 및 Infra 테스트 환경 설정 변경
  module-api/src/main/java/com/checkping/api/ApiApplication.java
  module-common/src/main/java/com/checkping/common/config/AuditorAwareImpl.java
  module-domain/src/main/java/com/checkping/domain/BaseEntity.java
  module-domain/src/main/java/com/checkping/domain/Member.java
  module-infra/build.gradle
  module-infra/src/main/java/com/checkping/infra/repository/MemberRepository.java
  module-infra/src/test/java/com/checkping/Application.java
  module-infra/src/test/java/com/checkping/infra/InfraApplicationTests.java
Labels: FEATURE

#74 fix : TaskBoard Enumerate 어노테이션 누락
  module-domain/src/main/java/com/checkping/domain/board/TaskBoard.java
Labels: ERROR

#86 Feature/83 feature 업체 수정
  module-api/src/main/java/com/checkping/api/controller/OrganizationController.java
  module-domain/src/main/java/com/checkping/domain/member/Organization.java
  module-service/src/main/java/com/checkping/dto/OrganizationRequest.java
  module-service/src/main/java/com/checkping/dto/OrganizationResponse.java
  module-service/src/main/java/com/checkping/service/member/OrganizationService.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
  module-service/src/test/java/com/checkping/service/OrganizationServiceTests.java
Labels: FEATURE

#128 Feature/127 JWT 페이로드 정보추가
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetails.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetailsService.java
  module-service/src/main/java/com/checkping/service/member/auth/ReissueService.java
  module-service/src/main/java/com/checkping/service/member/util/JwtUtil.java
Labels: FEATURE

#138 Feature/134 로그인 기능 수정
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
Labels: CHORE

#144 Feature/134 로그인 기능 수정
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
Labels: FEATURE

#143 Feature/117 feature 업무 관리 게시글 첨부 파일 추가 기능
  module-api/src/main/java/com/checkping/api/controller/TaskBoardController.java
  module-common/build.gradle
  module-common/src/main/java/com/checkping/common/utils/FileResponse.java
  module-domain/src/main/java/com/checkping/domain/board/TaskBoard.java
  module-domain/src/main/java/com/checkping/domain/board/TaskBoardFile.java
  module-infra/build.gradle
  module-infra/src/main/java/com/checkping/infra/repository/file/FileRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/file/LocalFileRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/file/S3FileRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/project/taskboardfile/TaskBoardFileStore.java
  module-infra/src/main/java/com/checkping/infra/repository/project/taskboardfile/TaskBoardFileStoreImpl.java
  module-service/src/main/java/com/checkping/dto/TaskBoardResponse.java
  module-service/src/main/java/com/checkping/service/project/TaskBoardFileService.java
  module-service/src/main/java/com/checkping/service/project/TaskBoardFileServiceImpl.java
  module-service/src/main/java/com/checkping/service/project/TaskBoardService.java
  module-service/src/main/java/com/checkping/service/project/TaskBoardServiceImpl.java
Labels: FEATURE

#154 fix : 프로젝트 전체 조회 시 업체 정보 없을 때 예외 처리
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: ERROR

#155 ERROR/CorsConfiguration 수정
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
Labels: ERROR

#164 Feature/151 chore dev profile 분리 및 mysql 서버 설정 수정
  .gitignore
  module-api/build.gradle
  module-api/src/main/resources/application-local.yaml
  module-api/src/main/resources/application-test.yaml
  module-api/src/main/resources/application.yaml
  module-common/src/main/resources/application.yaml
  module-domain/src/main/java/com/checkping/domain/project/Project.java
Labels: CHORE

#165 feat: 토근 발급 예외처리 추가
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-api/src/main/resources/application.yaml
  module-service/src/main/java/com/checkping/exception/auth/InvalidTokenException.java
  module-service/src/main/java/com/checkping/exception/auth/RefreshTokenCategoryException.java
  module-service/src/main/java/com/checkping/exception/auth/RefreshTokenExpiredException.java
  module-service/src/main/java/com/checkping/exception/auth/RefreshTokenNotFoundException.java
  module-service/src/main/java/com/checkping/exception/auth/TokenException.java
  module-service/src/main/java/com/checkping/service/member/auth/ReissueService.java
Labels: FEATURE

#167 fix : 설정 파일 이슈
  .gitignore
  module-api/src/main/resources/application-local.yaml
  module-api/src/main/resources/application.yaml
Labels: ERROR

#170 feat: 사용자 조회 기능 수정 및 사용자 조회 및 로그인 기능 예외처리 수정
  module-api/src/main/java/com/checkping/api/controller/MemberController.java
  module-api/src/test/java/com/checkping/api/MemberControllerTest.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-domain/src/main/java/com/checkping/domain/member/Member.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: FEATURE

#175 Feature/124 feature 프로젝트 생성 시 담당업체/담당자 정보 등록
  module-domain/src/main/java/com/checkping/domain/member/Organization.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#174 Feature/172 feature 업무 관리 게시글 목록 조회 개선
  module-api/src/main/java/com/checkping/api/controller/project/TaskBoardApi.java
  module-api/src/main/java/com/checkping/api/controller/project/TaskBoardController.java
  module-infra/src/main/java/com/checkping/infra/repository/project/taskboard/TaskBoardReader.java
  module-infra/src/main/java/com/checkping/infra/repository/project/taskboard/TaskBoardReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/project/taskboard/TaskBoardRepository.java
  module-service/src/main/java/com/checkping/dto/TaskBoardRequest.java
  module-service/src/main/java/com/checkping/service/project/TaskBoardServiceImpl.java
Labels: FEATURE

#186 fix : WebCorsConfig.java 삭제
  module-common/src/main/java/com/checkping/common/config/WebCorsConfig.java
Labels: ERROR

#190 chore : 멤버(회원 조회) 상세 내용에 소속 업체명 추가
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
Labels: CHORE

#184 Chore/156 로그인 기능 수정
  module-api/src/main/java/com/checkping/api/auth/filter/CustomLogoutFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/auth/util/ResponseUtil.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: CHORE

#181 feat : 비활성화된 회원 로그인 못하도록 기능 추가
  module-service/src/main/java/com/checkping/exception/auth/InactiveMemberException.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetailsService.java
Labels: FEATURE

#198 feat: 회원 조회 API에 페이징 기능 추가
  module-api/src/main/java/com/checkping/api/controller/member/MemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-infra/src/main/java/com/checkping/infra/repository/member/MemberRepository.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberListResponseDto.java
  module-service/src/main/java/com/checkping/exception/member/InvalidInputValueException.java
  module-service/src/main/java/com/checkping/exception/member/MemberException.java
  module-service/src/main/java/com/checkping/exception/member/MemberNotFoundException.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/test/java/com/checkping/service/MemberServiceTest.java
Labels: FEATURE

#192 feat : 프로젝트 수정 시 업체/담당자 수정
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#205 fix: 0번 페이지 조회 안되는 버그 수정
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: ERROR

#193 63 feature 프로젝트 관리단계 별 개수 조회
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#215 Feature/213-업체-exception-수정
  module-service/src/main/java/com/checkping/exception/member/OrganizationAlreadyExistEntityException.java
  module-service/src/main/java/com/checkping/exception/member/OrganizationException.java
  module-service/src/main/java/com/checkping/exception/member/OrganizationNotFoundEntityException.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: FEATURE

#221 feat : SwaggerConfig 설정 추가
  module-common/src/main/java/com/checkping/common/config/SwaggerConfig.java
Labels: SETTINGS

#227 fix : 테스트 및 개발 서버 스웨거 사용 가능하도록 구성
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
Labels: ERROR

#232 Feature/222 공지사항 생성
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-domain/src/main/java/com/checkping/domain/notice/Notice.java
  module-infra/src/main/java/com/checkping/infra/repository/notice/NoticeRepository.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeCreateRequestDto.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeResponseDto.java
  module-service/src/main/java/com/checkping/service/notice/NoticeService.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: FEATURE

#239 Feature/197 멤버 페이징 기능 구현
  module-api/src/main/java/com/checkping/api/controller/member/MemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-common/src/main/java/com/checkping/common/dto/PageMetaResponse.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberListResponseDto.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: FEATURE, CHORE

#250 Feat 241 JWT 토큰 저장 위치 변경
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/CustomLogoutFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/util/ResponseUtil.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-service/src/main/java/com/checkping/exception/auth/AccessTokenNotFoundException.java
  module-service/src/main/java/com/checkping/exception/auth/RefreshTokenNotFoundException.java
Labels: FEATURE

#252 Feature/214 feature 프로젝트 생성수정 수정
  module-domain/src/main/java/com/checkping/domain/project/ProgressStep.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepRepository.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#253 225 feature 프로젝트 조회 수정
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#254 Feature/223 feature 프로젝트 swagger 일괄 추가
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
Labels: FEATURE

#260 Chore : 멤버, 회원 Id 타입 Long으로 변경
  module-api/src/main/java/com/checkping/api/controller/member/MemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationApi.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationController.java
  module-domain/src/main/java/com/checkping/domain/member/Member.java
  module-domain/src/main/java/com/checkping/domain/member/Organization.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/repository/member/MemberRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/member/OrganizationRepository.java
  module-infra/src/test/java/com/checkping/infra/OrganizationRepositoryTests.java
  module-service/src/main/java/com/checkping/dto/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/ProjectResponse.java
  module-service/src/main/java/com/checkping/dto/member/request/MemberRegisterDto.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/OrganizationService.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: CHORE

#266 Feature/261 feature 프로젝트 목록 조회 페이징
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#271 Feature/257 feature 프로젝트 상태 별 목록 조회 기능 수정
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#244 Feature 240 공지사항 수정 기능 구현
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-domain/src/main/java/com/checkping/domain/notice/Notice.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeUpdateRequestDto.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponseDto.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeUpdateResponseDto.java
  module-service/src/main/java/com/checkping/service/notice/NoticeService.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: FEATURE

#275 Feature/242 feature 질문 게시글 목록 조회 기능
  module-api/src/main/java/com/checkping/api/controller/project/QuestionApi.java
  module-api/src/main/java/com/checkping/api/controller/project/QuestionController.java
  module-common/src/main/java/com/checkping/common/response/PaginationProps.java
  module-common/src/main/java/com/checkping/common/utils/DateTimeUtils.java
  module-domain/src/main/java/com/checkping/domain/question/Question.java
  module-domain/src/main/java/com/checkping/info/question/QuestionSearchInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReader.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionRepository.java
  module-service/src/main/java/com/checkping/dto/question/QuestionSearch.java
  module-service/src/main/java/com/checkping/dto/question/QuestionSearchCondition.java
  module-service/src/main/java/com/checkping/service/question/QuestionService.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#276 Chore/272 chore 운영 환경 설정 추가
  Dockerfile
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-common/src/main/java/com/checkping/common/config/SwaggerConfig.java
Labels: CHORE
