Repository Kernel360/KDEV3_FlowSync_BE, pull requests merged in 2025-02, with the labels that each got.

#289 Feature/268 feature 결재 목록 조회 기능
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-domain/src/main/java/com/checkping/info/approval/ApprovalSearchInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalRepository.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearch.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearchCondition.java
  module-service/src/main/java/com/checkping/exception/approval/ApprovalStatusException.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalService.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#284 chore: 프로젝트 register_id, updater_id, 관계테이블 컬럼 타입 변경
  module-domain/src/main/java/com/checkping/domain/project/Project.java
Labels: ERROR

#279 Feature/237 업체 페이징 기능 수정
  module-api/src/main/java/com/checkping/api/controller/MultipartJackson2HttpMessageConverter.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationApi.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationController.java
  module-common/src/main/java/com/checkping/common/dto/PageInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/member/OrganizationRepository.java
  module-infra/src/test/java/com/checkping/infra/OrganizationRepositoryTests.java
  module-service/src/main/java/com/checkping/service/member/OrganizationService.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
  module-service/src/test/java/com/checkping/service/OrganizationServiceTests.java
Labels: FEATURE

#298 Feature/251 로그인 로그아웃 컨트롤러 구현
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/CustomLogoutFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/auth/util/CookieUtil.java
  module-api/src/main/java/com/checkping/api/auth/util/ResponseUtil.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-api/src/main/java/com/checkping/api/controller/member/AuthApi.java
  module-api/src/main/java/com/checkping/api/controller/member/AuthController.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-service/src/main/java/com/checkping/dto/member/request/LoginRequestDto.java
  module-service/src/main/java/com/checkping/exception/auth/LoginException.java
  module-service/src/main/java/com/checkping/exception/auth/LoginFailureException.java
  module-service/src/main/java/com/checkping/exception/auth/LogoutException.java
  module-service/src/main/java/com/checkping/exception/auth/LogoutFailureException.java
  module-service/src/main/java/com/checkping/service/member/auth/AuthService.java
  module-service/src/main/java/com/checkping/service/member/auth/AuthTokens.java
Labels: FEATURE

#300 feat : 업체별 소속 회원 목록 조회 기능 추가
  module-api/src/main/java/com/checkping/api/controller/member/MemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-infra/src/main/java/com/checkping/infra/repository/member/MemberRepository.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: FEATURE

#295 277 feature 프로젝트 조회
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectUpdateDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/member/OrganizationRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#314 Chore/309 settings querydsl 셋팅
  module-domain/build.gradle
  module-infra/build.gradle
Labels: SETTINGS

#299 feat: 회원 목록 조회에 role/status 필터 및 검색 기능 추가
  module-api/src/main/java/com/checkping/api/controller/member/MemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-infra/src/main/java/com/checkping/infra/repository/member/MemberRepository.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
Labels: FEATURE

#316 Chore/285 me api 응답 타입 및 내용 변경
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-api/src/main/java/com/checkping/api/controller/member/AuthController.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
  module-service/src/main/java/com/checkping/service/member/auth/AuthService.java
Labels: CHORE

#319 Feat : JWT 토큰 페이로드 정보에 멤버 id 추가
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/controller/ReissueController.java
  module-service/src/main/java/com/checkping/service/member/auth/AuthService.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetails.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetailsService.java
  module-service/src/main/java/com/checkping/service/member/auth/ReissueService.java
  module-service/src/main/java/com/checkping/service/member/util/JwtUtil.java
Labels: FEATURE

#323 315 feature 고객 별 프로젝트 목록 조회 조건 추가
  module-infra/src/main/java/com/checkping/infra/dto/ProjectDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectListDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#325 324-feature : 프로젝트 파트 결재자 추가
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
Labels: FEATURE

#322 Chore/236 토큰 재발급 api swagger에 추가
  module-api/src/main/java/com/checkping/api/controller/member/auth/ReissueApi.java
  module-api/src/main/java/com/checkping/api/controller/member/auth/ReissueController.java
Labels: CHORE

#331 chore: Dockerfile 수정
  Dockerfile
Labels: CHORE

#334 chore: Health Check api 추가
  module-api/src/main/java/com/checkping/api/controller/DemoController.java
Labels: CHORE

#336 Feature/313 권한 설정 추가
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/config/InterceptorMvcConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/AuthInterceptor.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/GlobalExceptionHandler.java
  module-common/src/main/java/com/checkping/common/response/BaseResponse.java
  module-domain/src/main/java/com/checkping/domain/permission/MemberByProject.java
  module-domain/src/main/java/com/checkping/domain/permission/MemberByProjectId.java
  module-infra/src/main/java/com/checkping/infra/repository/permission/MemberByProjectRepository.java
  module-service/src/main/java/com/checkping/service/permission/MemberByProjectService.java
  module-service/src/main/java/com/checkping/service/permission/MemberByProjectServiceImpl.java
Labels: FEATURE

#337 chore : 프로젝트 목록 조회 수정
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
Labels: CHORE

#340 Feature/281 공지사항 기능 구현
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeApi.java
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-domain/src/main/java/com/checkping/domain/notice/Notice.java
  module-infra/src/main/java/com/checkping/infra/repository/notice/NoticeRepository.java
  module-service/src/main/java/com/checkping/dto/notice/NoticeContent.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeCreateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeCreateRequestDto.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeSearchRequest.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeUpdateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeUpdateRequestDto.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponseDto.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeGetListResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeListResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeUpdateResponseDto.java
  module-service/src/main/java/com/checkping/service/notice/NoticeService.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: FEATURE

#341 Chore/339 chore cookie setdomain 추가
  module-api/src/main/java/com/checkping/api/auth/util/CookieUtil.java
  module-api/src/main/resources/logback-spring.xml
Labels: CHORE

#350 chore : 엑세스 토큰 검증 시, 응답 값 수정
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
Labels: ERROR, CHORE

#343 Chore/342 health-check api 허용
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
Labels: CHORE

#348 Feature/346 업체 목록 정렬 추가
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: FEATURE

#362 chore: TimeZone 수정
  Dockerfile
Labels: CHORE

#360 Chore/349 chore 개발사 프로젝트 목록 조회 수정
  module-infra/src/main/java/com/checkping/infra/dto/ProjectListDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: CHORE

#390 Feature/385 feature 특정 관리단계 별 프로젝트 목록 조회
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/projection/ProjectListInfoByManagementStep.java
  module-infra/src/main/java/com/checkping/infra/repository/project/querydsl/ProjectRepositoryCustom.java
  module-infra/src/main/java/com/checkping/infra/repository/project/querydsl/ProjectRepositoryImpl.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#391 fix/385 ProjectServiceImpl 충돌 수정
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: ERROR

#357 chore: 레디스 설정 및 import 문 추가
  module-api/src/main/resources/application-local.yaml
Labels: CHORE

#375 Feature/364 feature 결재 연관관계 맵핑
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-domain/src/main/java/com/checkping/domain/approval/Approval.java
  module-domain/src/main/java/com/checkping/domain/approval/ApprovalComment.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepReader.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectReader.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalConfirm.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalGet.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalRegister.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearch.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentGet.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentRegister.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalReCommentRegister.java
  module-service/src/main/java/com/checkping/dto/approval/file/ApprovalFileRegister.java
  module-service/src/main/java/com/checkping/dto/approval/link/ApprovalLinkRegister.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepGet.java
  module-service/src/main/java/com/checkping/exception/approval/ApprovalAuthorityException.java
  module-service/src/main/java/com/checkping/exception/project/ProjectException.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepException.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepMismatchProjectException.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepNotFoundException.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalService.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#388 Feature/231 feature 결재 승인 기능
  module-domain/src/main/java/com/checkping/domain/approval/Approval.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#393 Feature/383 feature 프로젝트 진행 단계 조회
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepGet.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepMismatchMemberException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepService.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: FEATURE

#379 Feature/365 feature 결재 수정 기능
  module-service/src/main/java/com/checkping/dto/approval/ApprovalUpdate.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#404 feat : 로그아웃 전에 레디스 연결 여부 확인하도록 수정
  module-service/src/main/java/com/checkping/service/member/auth/AuthService.java
Labels: FEATURE

#405 Feature/363 관리자 회원 상태 변경 및 차단 기능 구현, 권한 없는 요청 응답 메시지 적용
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberController.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/CustomAccessDeniedHandler.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-domain/src/main/java/com/checkping/domain/member/Member.java
  module-service/src/main/java/com/checkping/dto/member/request/LoginRequestDto.java
  module-service/src/main/java/com/checkping/dto/member/request/MemberRegisterDto.java
  module-service/src/main/java/com/checkping/dto/member/request/MemberUpdateDto.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/auth/CustomUserDetailsService.java
Labels: FEATURE

#409 Chore/389 chore 프로젝트 엔티티 status 제거
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectUpdateDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/project/projection/ProjectInfoProjection.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: CHORE

#406 Feature/368 feature결재 상세 조회 시 서명 정보 조회
  module-domain/src/main/java/com/checkping/domain/approval/Approval.java
  module-domain/src/main/java/com/checkping/domain/member/Member.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalConfirm.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalGet.java
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
Labels: FEATURE

#407 Feature/402 feature 결재 게시글 개수 조회 기능
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-domain/src/main/java/com/checkping/info/approval/ApprovalCountProjection.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalRepository.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalCount.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalService.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#408 Feature/403 feature 결재 목록 조회 수정
  module-domain/src/main/java/com/checkping/info/approval/ApprovalSearchInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalRepository.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearch.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearchCondition.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#415 Feature/411 feature 프로젝트 별 정보 조회 시 관리단계 결재자 정보 조회
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/projection/OwnerInfo.java
  module-domain/src/main/java/com/checkping/domain/project/projection/ProjectInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/project/querydsl/ProjectRepositoryCustom.java
  module-infra/src/main/java/com/checkping/infra/repository/project/querydsl/ProjectRepositoryImpl.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#416 Feature/398 feature 프로젝트 진행 단계 엔티티 변경
  module-domain/src/main/java/com/checkping/domain/project/ProgressStep.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepGet.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#417 Feature/413 결재 요청 권한 체크 기능 구현 - 결재 조회, 등록, 수정, 삭제
  module-api/src/main/java/com/checkping/api/auth/config/InterceptorMvcConfig.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/ApprovalAuthorizationInterceptor.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/AuthInterceptor.java
Labels: FEATURE

#418 Feature/327 Redis 연결 체크 로직 개선 및 JWT 예외 처리 개선
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-service/src/main/java/com/checkping/service/member/auth/TokenBlacklistService.java
Labels: CHORE

#423 Feature/392 feature 결재 유형 추가
  module-domain/src/main/java/com/checkping/domain/approval/Approval.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalConfirm.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalGet.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalRegister.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalSearch.java
  module-service/src/main/java/com/checkping/exception/approval/ApprovalCategoryException.java
Labels: FEATURE

#422 feature/410 feature 프로젝트 관리단계 수정 api 생성
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-domain/src/main/java/com/checkping/domain/project/projection/ProjectInfo.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectUpdateDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/project/querydsl/ProjectRepositoryImpl.java
  module-infra/src/test/java/com/checkping/infra/ProjectRepositoryTests.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
  module-service/src/test/java/com/checkping/service/ProjectServiceTests.java
Labels: FEATURE

#429 fix : 병합 시 누락된 코드 추가
  module-api/src/main/java/com/checkping/api/controller/ProjectApi.java
Labels: ERROR

#430 [FEATURE] 결재 승인/반려 인가 검사 기능 추가 코드 개선
  module-api/src/main/java/com/checkping/api/auth/interceptor/ApprovalAuthorizationInterceptor.java
Labels: FEATURE

#433 공지사항 DTO 수정
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponse.java
Labels: FEATURE

#438 Feature/437 feature 결재 댓글 수정 삭제 기능
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-domain/src/main/java/com/checkping/domain/approval/ApprovalComment.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentDelete.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentUpdate.java
  module-service/src/main/java/com/checkping/exception/approval/comment/ApprovalCommentNotRegisterException.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalAuthorizationValidator.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalService.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#439 Feature/291 feature 질문 게시글 연관관계 맵핑
  module-api/src/main/java/com/checkping/api/controller/question/QuestionApi.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-domain/src/main/java/com/checkping/domain/question/Question.java
  module-domain/src/main/java/com/checkping/domain/question/QuestionComment.java
  module-service/src/main/java/com/checkping/dto/question/QuestionGet.java
  module-service/src/main/java/com/checkping/dto/question/QuestionRegister.java
  module-service/src/main/java/com/checkping/dto/question/QuestionRequest.java
  module-service/src/main/java/com/checkping/dto/question/QuestionResponse.java
  module-service/src/main/java/com/checkping/dto/question/QuestionSearch.java
  module-service/src/main/java/com/checkping/dto/question/comment/QuestionCommentGet.java
  module-service/src/main/java/com/checkping/dto/question/comment/QuestionCommentRegister.java
  module-service/src/main/java/com/checkping/dto/question/comment/QuestionCommentResponse.java
  module-service/src/main/java/com/checkping/dto/question/comment/QuestionReCommentRegister.java
  module-service/src/main/java/com/checkping/dto/question/link/QuestionLinkRegister.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
  module-service/src/main/java/com/checkping/service/question/comment/QuestionCommentServiceImpl.java
Labels: FEATURE

#442 Feature/435 회원 비활성화 기능 수정
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-common/src/main/java/com/checkping/common/config/RedisConfig.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/auth/AuthService.java
  module-service/src/main/java/com/checkping/service/member/auth/RedisConnectionCheckService.java
  module-service/src/main/java/com/checkping/service/member/auth/ReissueService.java
  module-service/src/main/java/com/checkping/service/member/auth/TokenBlacklistService.java
Labels: FEATURE

#434 412 feature 프로젝트 목록 조회 시 정렬 기능 추가
  module-api/src/main/java/com/checkping/api/controller/project/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-infra/src/main/java/com/checkping/infra/dto/ProjectUpdateDetailsDto.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProjectRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
  module-service/src/main/java/com/checkping/dto/project/ProjectSearchRequest.java
  module-service/src/main/java/com/checkping/service/project/ProjectService.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#446 [REFACTOR] 445 memberservice 인터페이스 및 구현체 분리
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberApi.java
  module-service/src/main/java/com/checkping/dto/member/request/ChangePasswordDto.java
  module-service/src/main/java/com/checkping/dto/member/request/MemberRegisterDto.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
Labels: REFACTOR

#441 fix : 결재 상세 조회 시 댓글이 없으면 조회가 안되는 이슈 해결
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
Labels: ERROR

#448 chore : 충돌 해결하며 누락된 코드 반영
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
  module-service/src/main/java/com/checkping/service/member/auth/RedisConnectionCheckService.java
Labels: CHORE

#447 Feature/443 feature 질문 게시글 서비스 권한 체크
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-common/src/main/java/com/checkping/common/utils/AbstractAuthorizationValidator.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalAuthorizationValidator.java
  module-service/src/main/java/com/checkping/service/question/QuestionAuthorizationValidator.java
  module-service/src/main/java/com/checkping/service/question/QuestionService.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#458 Error/456 403에러 응답 본문 누락 문제
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/CustomAccessDeniedHandler.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/CustomAuthenticationEntryPoint.java
Labels: ERROR

#452 feat: 회원 목록 조회 기능 개선 및 정렬 기능 추가 및 인터셉터 비활성화
  module-api/src/main/java/com/checkping/api/auth/config/InterceptorMvcConfig.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/ApprovalAuthorizationInterceptor.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/AuthInterceptor.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberController.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
Labels: FEATURE

#451 Feature/306 feature 질문 게시글 답글 생성 기능
  module-api/src/main/java/com/checkping/api/controller/question/QuestionApi.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-domain/src/main/java/com/checkping/domain/question/Question.java
  module-service/src/main/java/com/checkping/dto/question/QuestionGet.java
  module-service/src/main/java/com/checkping/dto/question/QuestionParentAnswer.java
  module-service/src/main/java/com/checkping/dto/question/QuestionRegister.java
  module-service/src/main/java/com/checkping/service/question/QuestionService.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#454 fix : 프로젝트 진행 단계 조회 권한 처리
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: ERROR

#461 Refactor/업체 목록 조회 정렬 기준 추가
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationApi.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationController.java
  module-service/src/main/java/com/checkping/service/member/OrganizationService.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: REFACTOR

#455 Error/425 업체 소속 회원 조회 시 회원이 없는 업체를 조회하면 404 에러가 발생하는 이슈
  module-api/src/main/java/com/checkping/api/auth/util/CookieUtil.java
  module-api/src/main/resources/application.yaml
Labels: CHORE

#465 Feature/394 feature 완료 결재 로그 추가 기능 및 목록 조회 기능
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-domain/src/main/java/com/checkping/domain/approval/ApprovalCompleteHistory.java
  module-domain/src/main/java/com/checkping/info/approval/ApprovalCompleteHistorySearchInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryStore.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCompleteHistoryStoreImpl.java
  module-service/src/main/java/com/checkping/dto/approval/history/complete/ApprovalCompleteHistoryInfo.java
  module-service/src/main/java/com/checkping/dto/approval/history/complete/ApprovalCompleteHistorySearch.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalService.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: FEATURE

#463 Feature/427 공지사항 첨부파일 추가
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeApi.java
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-domain/src/main/java/com/checkping/domain/notice/Notice.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeCreateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeUpdateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithoutIsdeletedResponse.java
  module-service/src/main/java/com/checkping/service/notice/NoticeService.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: FEATURE

#468 Fix/459 error 프로젝트 진행 단계 날짜 수정 시 에러
  module-domain/src/main/java/com/checkping/domain/project/ProgressStep.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepGet.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepPlanUpdate.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepNotAfterStartAtException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: ERROR

#477 chore: 회원 활성화 로직 수정
  module-domain/src/main/java/com/checkping/domain/member/Member.java
Labels: CHORE

#482 Feature/481 jwt 검증 필터 예외처리 추가
  module-api/src/main/java/com/checkping/api/auth/filter/CustomLogoutFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/filter/LoginFilter.java
  module-api/src/main/java/com/checkping/api/auth/util/ResponseUtil.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/CustomAccessDeniedHandler.java
  module-api/src/main/java/com/checkping/api/exceptionhandler/CustomAuthenticationEntryPoint.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-service/src/main/java/com/checkping/service/member/util/JwtUtil.java
Labels: FEATURE

#469 Feature/업체에 속한 회원 조회 필터링 추가
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberApi.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberController.java
  module-infra/src/main/java/com/checkping/infra/repository/member/MemberRepository.java
  module-service/src/main/java/com/checkping/service/member/MemberService.java
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
Labels: FEATURE

#492 Feature/427 공지사항 첨부파일 추가
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeApi.java
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-infra/src/main/java/com/checkping/infra/repository/notice/NoticeRepository.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeCreateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/request/NoticeUpdateRequest.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithoutIsdeletedResponse.java
  module-service/src/main/java/com/checkping/service/notice/NoticeService.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: FEATURE

#470 Feature/318 feature 질문 게시글 목록 조회 수정
  module-api/src/main/java/com/checkping/api/controller/question/QuestionApi.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-domain/src/main/java/com/checkping/info/question/QuestionSearchInfo.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionRepository.java
  module-service/src/main/java/com/checkping/dto/question/QuestionSearchCondition.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#471 feat : Request Dto 유효성 검사
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalApi.java
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalRegister.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalUpdate.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentRegister.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentUpdate.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalReCommentRegister.java
Labels: ERROR, FEATURE

#473 fix : 결재 상세 조회 시 댓글이 없을 때 처리
  module-service/src/main/java/com/checkping/dto/approval/ApprovalGet.java
Labels: ERROR

#483 Fix/480 error 진행단계 날짜 설정 시 null 처리
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepStartAtException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: FEATURE

#490 fix : 프로젝트 진행 단계 조회 시 누락된 regAt 추가
  module-service/src/main/java/com/checkping/dto/approval/history/complete/ApprovalCompleteHistorySearch.java
Labels: ERROR

#491 feat : 요청 성공 시 메시지 추가
  module-api/src/main/java/com/checkping/api/controller/approval/ApprovalController.java
  module-api/src/main/java/com/checkping/api/controller/file/FileController.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberController.java
  module-api/src/main/java/com/checkping/api/controller/member/MemberController.java
  module-api/src/main/java/com/checkping/api/controller/notice/NoticeController.java
  module-api/src/main/java/com/checkping/api/controller/organization/OrganizationController.java
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-common/src/main/java/com/checkping/common/enums/SuccessCode.java
Labels: FEATURE

#496 chore : 프로젝트 목록 조회 시 시간 데이터 형식 수정
  module-service/src/main/java/com/checkping/dto/project/ProjectResponse.java
Labels: CHORE

#499 Refactor/업체명 공백 제거
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: REFACTOR

#502 fix : 공지사항 예외처리 수정
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithIsdeletedResponse.java
Labels: ERROR

#504 Feature/62 시스템 컬럼 생성자 수정자 id 인증기능 구현
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-common/src/main/java/com/checkping/common/config/AuditorAwareImpl.java
Labels: FEATURE

#498 Feature/493 삭제된 회원이 요청 보낼 수 없도록 하는 기능추가
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/controller/member/AdminMemberController.java
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
Labels: FEATURE

#506 Feature/494 feature 프로젝트 예외처리 검증 추가
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/Project.java
  module-service/src/main/java/com/checkping/dto/project/ProjectRequest.java
  module-service/src/main/java/com/checkping/dto/project/ProjectSearchRequest.java
  module-service/src/main/java/com/checkping/exception/project/InvalidProjectDataException.java
  module-service/src/main/java/com/checkping/exception/project/ProjectAlreadyDeletedException.java
  module-service/src/main/java/com/checkping/exception/project/ProjectNotFoundException.java
  module-service/src/main/java/com/checkping/exception/project/ProjectStepCreationException.java
  module-service/src/main/java/com/checkping/exception/project/ProjectUpdatePermissionException.java
  module-service/src/main/java/com/checkping/service/project/ProjectServiceImpl.java
Labels: FEATURE

#500 Feature/486 feature 프로젝트 진행 단계 수정하기 기능
  module-api/src/main/java/com/checkping/api/controller/project/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-domain/src/main/java/com/checkping/domain/project/ProgressStep.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepOrderUpdater.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepUpdateSizeException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepService.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: FEATURE

#505 Feature/487 feature 프로젝트 진행 단계 삭제 기능
  module-api/src/main/java/com/checkping/api/controller/project/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-common/src/main/java/com/checkping/common/enums/SuccessCode.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepStore.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepStoreImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReader.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionRepository.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepDelete.java
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepExistsBoardException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepService.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: FEATURE

#509 Feature/386 feature s3 file download presigned url 기능
  module-common/src/main/java/com/checkping/common/config/S3Config.java
  module-infra/src/main/java/com/checkping/infra/repository/file/FileReader.java
  module-infra/src/main/java/com/checkping/infra/repository/file/FileReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/file/FileRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/file/LocalFileRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/file/S3FileRepositoryImpl.java
Labels: FEATURE

#511 chore: CORS, check API 설정 수정
  module-api/src/main/java/com/checkping/api/auth/config/CustomSecurityConfig.java
Labels: CHORE

#514 Error/513 error 프로젝트 진행 단계 순서 수정 삭제 api
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/project/ProgressStepRepository.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalCount.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepDelete.java
  module-service/src/main/java/com/checkping/dto/question/QuestionCounter.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: ERROR

#512 Feature/508 따닥 방지 구현 (Redis 상태 확인 후 중복 클릭 방지 인터셉터 등록)
  module-api/src/main/java/com/checkping/api/auth/config/InterceptorMvcConfig.java
  module-api/src/main/java/com/checkping/api/auth/filter/JWTFilter.java
  module-api/src/main/java/com/checkping/api/auth/interceptor/DuplicatedClickPrevent.java
  module-common/src/main/java/com/checkping/common/config/RedisConfig.java
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-service/src/main/java/com/checkping/exception/request/DuplicateRequestException.java
  module-service/src/main/java/com/checkping/service/member/MemberServiceImpl.java
Labels: FEATURE

#533 ERROR/427 공지사항 에러 해결
  module-common/src/main/java/com/checkping/common/enums/ErrorCode.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeGetListWithIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeGetListWithoutIsdeletedResponse.java
  module-service/src/main/java/com/checkping/service/notice/NoticeServiceImpl.java
Labels: ERROR

#521 Error/515 error 결재 게시글 목록 작성일 기준으로 정렬
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionCustomRepositoryImpl.java
Labels: ERROR

#530 Error/526 error 댓글 삭제 시 deleteyn 으로 주기
  module-domain/src/main/java/com/checkping/domain/approval/ApprovalComment.java
  module-domain/src/main/java/com/checkping/domain/question/QuestionComment.java
  module-service/src/main/java/com/checkping/dto/approval/comment/ApprovalCommentGet.java
  module-service/src/main/java/com/checkping/dto/question/comment/QuestionCommentGet.java
Labels: ERROR

#523 Refactor/520 업체 파일 Presigned-URL 변경
  module-common/src/main/java/com/checkping/common/config/S3Config.java
  module-service/src/main/java/com/checkping/dto/OrganizationListGet.java
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: REFACTOR

#529 Refactor/525 업체 modify 수정
  module-service/src/main/java/com/checkping/service/member/OrganizationServiceImpl.java
Labels: REFACTOR

#536 feat: S3 Public 저장소 추가
  module-infra/src/main/java/com/checkping/infra/repository/file/S3PublicFileRepositoryImpl.java
Labels: FEATURE

#538 HOTFIX: Redis 저장소 문제 해결 (@Qualifier 적용)
  module-service/src/main/java/com/checkping/service/member/auth/TokenBlacklistService.java
Labels: ERROR

#539 Feature/527 feature 프로젝트 진행 단계 별 색상 커스텀 기능
  module-api/src/main/java/com/checkping/api/controller/project/ProjectApi.java
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-domain/src/main/java/com/checkping/domain/project/ProgressStep.java
  module-domain/src/main/java/com/checkping/info/approval/ApprovalCountProjection.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-service/src/main/java/com/checkping/dto/approval/ApprovalCount.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepGet.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepOrderUpdater.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepPlanUpdate.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepRegister.java
  module-service/src/main/java/com/checkping/dto/project/ProgressStepUpdater.java
  module-service/src/main/java/com/checkping/dto/question/QuestionCounter.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepService.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: FEATURE

#540 Feature/531 feature 질문 해결 api 기능 개발
  module-api/src/main/java/com/checkping/api/controller/question/QuestionApi.java
  module-api/src/main/java/com/checkping/api/controller/question/QuestionController.java
  module-domain/src/main/java/com/checkping/domain/question/Question.java
  module-service/src/main/java/com/checkping/service/question/QuestionService.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#542 feat : 결재, 질문, 댓글 작성자 정보 수정
  module-service/src/main/java/com/checkping/dto/member/response/MemberResponseDto.java
Labels: FEATURE

#543 Feature/522 feature 결재 질문 첨부파일 링크 presigned url 로 반환하도록 변경
  module-api/src/main/java/com/checkping/api/controller/file/FileApi.java
  module-api/src/main/java/com/checkping/api/controller/file/FileController.java
  module-common/src/main/java/com/checkping/common/enums/SuccessCode.java
  module-infra/src/main/java/com/checkping/infra/repository/file/PublicFileReader.java
  module-infra/src/main/java/com/checkping/infra/repository/file/PublicFileReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/file/PublicFileStore.java
  module-infra/src/main/java/com/checkping/infra/repository/file/PublicFileStoreImpl.java
  module-service/src/main/java/com/checkping/dto/approval/file/ApprovalFileGet.java
  module-service/src/main/java/com/checkping/dto/question/file/QuestionFileRegister.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
  module-service/src/main/java/com/checkping/service/file/FileService.java
  module-service/src/main/java/com/checkping/service/file/FileServiceImpl.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#545 fix : 결재 댓글 권한 처리 에러
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/comment/ApprovalCommentRepository.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalAuthorizationValidator.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
Labels: ERROR

#547 공지사항 DTO 날짜수정
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeCreateResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeGetListWithIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeGetListWithoutIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithIsdeletedResponse.java
  module-service/src/main/java/com/checkping/dto/notice/response/NoticeWithoutIsdeletedResponse.java
Labels: ERROR

#551 Error/550 error 진행 단계 작업 시 권한 관리
  module-service/src/main/java/com/checkping/exception/project/progressstep/ProgressStepNotDevOwnerException.java
  module-service/src/main/java/com/checkping/service/project/progressstep/ProgressStepServiceImpl.java
Labels: ERROR

#553 fix : 질문 게시글 개수에서 삭제된 게시글 필터링
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionRepository.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: ERROR

#555 Feature/554 feature 관리자 접속 시 결재 질문 목록 전체 조회
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepository.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalCustomRepositoryImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReader.java
  module-infra/src/main/java/com/checkping/infra/repository/approval/ApprovalReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReader.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionReaderImpl.java
  module-infra/src/main/java/com/checkping/infra/repository/question/QuestionRepository.java
  module-service/src/main/java/com/checkping/service/approval/ApprovalServiceImpl.java
  module-service/src/main/java/com/checkping/service/question/QuestionServiceImpl.java
Labels: FEATURE

#557 fix : 프로젝트 진행 단계 수정 완료 시 메세지 출력
  module-api/src/main/java/com/checkping/api/controller/project/ProjectController.java
Labels: ERROR
